name: v1-hdmi-rpi3
on: workflow_dispatch


jobs:
  os:
    uses: hvillar/os/.github/workflows/os.yml@master
    with:
      BOARD: rpi3
      PLATFORM: v1-hdmiusb
    secrets:
      DEPLOY_KEY: "${{secrets.WORKFLOW_TOKEN}}"
